### ISSUE TITLE
Code folding?

### ISSUE THREAD

**Issue by NevilleDNZ** [TrisTOON/language-algol60#2]
Nice and simple code highlighter.

Even supports ×, ÷, ≤, ≥, ≠, ¬, ∨, ∧, ⊂, ≡ and the Буран "⏨" eg. 6.02214179⏨23

However: 
 - Code folding of begin/end blocks doesn't seem to work is VSCode
 - It may be I don't know how to turn code folding on...

cf. https://stackoverflow.com/questions/35854584/vscode-code-folding

**Comment by PolariTOON** [comment]
Thanks for the report!

You're right there is a bug with the begin/end blocks because i made a mistake when i ported the extension from Atom to Visual Studio Code.

I will publish a fix soon!

**Comment by NevilleDNZ** [comment]
v0.5.1 with code folding update "spontaneously" installed on my PC's VSCode this morning... fast work, many ThanX.
