### ISSUE TITLE
VSCode: Level 2 snippets need to be cursor juggled

### ISSUE THREAD

**Issue by NevilleDNZ** [TrisTOON/language-algol60#3]
I tried **language-algol60** snippets on _atom_ and _VSCode_ and the functionality differs... slightly.

example code:
```
begin
    begin_
end
```

Basically:
- on _atom_ when the cursor gets to "_" (in code above) I get the choice of adding a matching block `end` ... perfect.
- on _VSCode_, when the cursor gets to "_" `begin` gets **bolded**, but no `end` choice is offered.

It seems that when there are remaining unfilled **fields**, the next snippet `begin-end` wont be offered.

However I found the **workaround** (needed on _VSCode_) is to juggle the cursor (eg. ←→) _before_ I type the second `begin` so then **language-algol60** presents me with the option of adding a matching block `end`...

Hints welcomed...

**Comment by PolariTOON** [comment]
You're right it seems that in Visual Studio Code, snippets are not suggested when already editing a suggestion.

I tried a bit and it seems to be the case in other languages too and not only this extension.
Since i'm not aware of any way to change that behavior, i think this issue is not related to this extension.

I don't know enough about Visual Studio Code but i just found you can press the `Escape` key *before* starting to type the second `begin` to get back to normal editing mode. Yay!

I'll close this issue then. :wink:

**Comment by NevilleDNZ** [comment]
I hear what you are saying. I just tried AdaCore and Pascal on VSCode and level2 begin/ends snippet insertion seem to work.

So, I'll check to see how it's done with Pascal and Ada.  

However, I quite like the language-algol60 extension as it mostly works on atom and VSCode...

I'm kind of curious to know how compatible extension are between atom and VSCode... for example I notice that AdaCode has not made it to atom.  Are there big hurdles migrating extensions between these two IDEs?

BTW: I've spotted various references to a mysterious "tiger" in ./grammars/language-algol60.json, eg.
 - "name": "storage.type.bool.tiger",
 - "name": "storage.type.int.tiger",
 - "name": "storage.type.re.tiger",
 - "name": "storage.type.str.tiger",
 - "name": "storage.type.lbl.tiger",

**Comment by PolariTOON** [comment]
> I just tried AdaCore and Pascal on VSCode and level2 begin/ends snippet insertion seem to work.

I will search a bit more how to make it work then. :wink:

> I'm kind of curious to know how compatible extension are between atom and VSCode... for example I notice that AdaCode has not made it to atom. Are there big hurdles migrating extensions between these two IDEs?

Both Atom and Visual Studio Code support TextMate grammars and snippets (mostly auto-completion).

Atom always search the files in the `grammars` and `snippets` folders respectively, but not Visual Studio Code, so i just make Visual Studio Code know the files are there.

However, syntax and behavior for settings (whitespace, comments, folding and indentation) are incompatible between the two editors, so i have to set them twice.

> BTW: I've spotted various references to a mysterious "tiger" in ./grammars/language-algol60.json

Oops, bad copy-paste from another extension i wrote; i will fix that in the next days (but i would love to have a PR too!). Thanks for noticing!
